
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = ( <p>asdf</p>)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-32 container-custom">
        {children}
        </div>
        <LoginModal />
        {/* <Modal
        label="Modal tests"
        content={content}
        isOpen={true}/> */}
      </body>
    </html>
  );
}
